name: Events Demo 1
on:
  pull_request:
    types: 
      - opened

  workflow_dispatch:
  push:
    branches:
      - main      # Triggers on pushes to the exact branch named 'main'
      - "dev-*"   # Triggers on pushes to branches starting with 'dev-' (e.g., dev-feature; does not match slashes)
      - "feat/**" # Triggers on pushes to branches starting with 'feat/' and any nested sub-branches (e.g., feat/ui, feat/api/auth)
    paths-ignore:
      - '.github/workflows/**'  #Workflow won't trigger if changes are only in these paths (e.g. documentation, workflow files)
    # paths:
    #   - 'src/**'             # Workflow triggers ONLY when changes are made to these paths.
    #   # NOTE: You cannot use both 'paths' and 'paths-ignore' for the same event in a workflow.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."